### ISSUE TITLE
デザインの作成

### ISSUE THREAD

**Issue by Junkichi89** [if-tech-support/todo_team#11]
## 実装内容の説明
- UIのついたIssuごとのワイヤーフレームを作成する

## TASK
- [ ] UIのついたIssuごとのワイヤーフレームを作成する

## その他・備考
-

**Comment by tsubasa-tahara** [comment]
作成したデザインリンクを共有
https://www.figma.com/file/86QSmuMKTkcyL6Jxo3nG93/Todo%E3%82%A2%E3%83%97%E3%83%AA%E9%96%8B%E7%99%BA?node-id=0%3A1
