### ISSUE TITLE
【機能】タスクをクリックで詳細画面に遷移　

### ISSUE THREAD

**Issue by Junkichi89** [if-tech-support/todo_team#23]
## 実装内容の説明
- タスク名をクリックすると`/detai`画面に遷移し、クリックしたタスクの詳細な情報を確認することができる
- 

## TASK
- [x] ボタンクリックで画面が遷移できる
- [ ] 遷移した画面にクリックしたタスクの詳細な内容が表示される
- [ ] （編集画面に遷移することができる）

## その他・備考
- 余裕があれば、追加で編集画面へ遷移の実装

**Comment by tsubasa-tahara** [comment]
![image](https://user-images.githubusercontent.com/83959151/143675332-2fe7202e-c16b-4117-88b4-683c3abbe76e.png)
ボタンをクリックで画面遷移ができるは完了
実際にyarn addした後、localhostの画面でタスク名を押下するとDetail画面へ遷移することを確認

遷移した画面にタスクの詳細な内容が表示されるに着手

**Comment by tsubasa-tahara** [comment]
## 作業メモ
参考リンク
https://qiita.com/ppt_msdg_maas/items/28ed1cfbe2eb1f84eeb7

- atom.jsに以下を
 ```
const [todos, setTodos] = useState([])
 const [todoTitle, setTodoTitle] = useState("")
 const [todoDetail, setTodoDetail] = useState("")
 const [todoId, setTodoId] = useState(0)
```

```
export const memoAtomState = atom<string[]>({
  key: "memoAtom",
  default: [],
});
```
のような感じで記述してstateを初期化する。

- その後にDetail.jsxで以下のようなコードを記述する。Detailは読み取り専用のページ
`const memos = useRecoilValue<string[]>(memoAtomState);`
そしてmap(todo,index)みたいな感じで取り出す。
ただしキーにindexは使わない方がいいとどこかのプルリクで見た。

**Comment by tsubasa-tahara** [comment]
単純に画面遷移ではなく、router.pushみたいな感じでステートを渡さないといけない
